### PR TITLE
removed dsh config

### PR DESCRIPTION
**Pull request by jonnysamps**
@johnmendonca @quady please review.  This PR is intended to stop the CAC from spinning up dashboards per constellation.

### CODE REVIEW

**Comment by johnmendonca** [comment]
The configurator also has a yml file like this you'll want to check on.  I forget if it is there or here or both, but removing a config section like this will break the app, because of the existing db records of type dsh.  Whenever you deploy this you will need to also delete all the app records in the db of this type.  Probably @johnlucia was the last one to run into this.  Otherwise :+1:

**Comment by jonnysamps** [comment]
Good note @johnmendonca , thanks!

**Comment by jonnysamps** [comment]
@johnmendonca added a migration to remove the client apps for dashboard.  Can you include this in your normal release process?

**Comment by quady** [comment]
Ran a test on T1 and no dsh was spun up. :+1:

**Pull request merged**
