### PR TITLE
After auth tasks and ps scaling

### PR DESCRIPTION
**Pull request by perryqh**
CLS needs to run a rake task after Auth has been setup. This rake task also needs a "worker". https://www.pivotaltracker.com/story/show/109760688
- added "after_auth_setup_tasks" to defaults.yml as a place to add tasks that will be ran after auth is setup
- added "ps_scale" to defaults.yml for scaling up processes
- extracted provisioning classes to own files
- introduced provisioner factory for testability
- introduced resque_spec to reduce a bunch of Resqueue.stub code

### CODE REVIEW

**Comment by ryankbales** [comment]
@perryqh Would you mind expanding upon what this pull request does or provide a PT story link?  Looks like some major changes happening for such a short PR description.  Thank you sir!

**Comment by ryankbales** [comment]
I could also look at the commit messages too I guess.  :)

**Comment by perryqh** [comment]
@ryankbales I updated the description. You're right in that it much too terse!

**Comment by ryankbales** [comment]
Thanks @perryqh I presume it will or already has gone through testing so :ship: it.  Also, thanks for abstracting some of those classes.  A couple of those files were getting pretty big.  Nice work!

**Comment by johnmendonca** [comment]
:+1: looks good

**Pull request merged**
