### PR TITLE
Add a first pass as CLS/CXM environment variables.

### PR DESCRIPTION
**Pull request by dpetersen**
These two are mostly copies of existing setup. We have a bunch of comments for things we want to work on after we've seen this working. Each one is going to require a little bit of code and I don't want to try and do it all at once.

### CODE REVIEW

**Comment by johnmendonca** [comment]
This has been covered by https://github.com/G5/g5-client-app-creator/pull/55

**Comment by dpetersen** [comment]
I'm going to need super admin account to test these changes before I can accept your story.

**Comment by quady** [comment]
@dpetersen here you go, root access to the server, test whatever you want: http://bit.ly/1gsOvva

**Comment by dpetersen** [comment]
[I KNOW THIS](http://www.youtube.com/watch?v=3HjOjvu6oKA)

**Comment by quady** [comment]
http://i.imgur.com/XS5LK.gif

**Comment by jcstringer** [comment]
@dpetersen boy do we miss you and your dry humor around here ;-)

**Pull request closed without merging**
