### PR TITLE
add FURY_AUTH to cms

### PR DESCRIPTION
**Pull request by thescubageek**
The title says it all....

### CODE REVIEW

**Comment by variousred** [comment]
@thescubageek What's this for?

**Comment by thescubageek** [comment]
So we don't have to keep adding/removing the Gem Fury token from the Gemfile for the CMS... makes it an ENV var, which is how the rest of our apps do it. I've added the FURY_AUTH var to all the existing CMSs already...

**Comment by variousred** [comment]
Dont they spin up fine without it? I just created a CMS yesterday and didnt have to add a var

**Comment by variousred** [comment]
Oh, i see the token was added back to the Gemfile 25 days ago

**Comment by variousred** [comment]
:shipit:

**Pull request merged**
