### PR TITLE
Remove garden env vars from CMS spinup, because eff microformats

### PR DESCRIPTION
**Pull request by thescubageek**
Removes the following deprecated ENV vars from the CMS:

* LAYOUT_GARDEN_URL
* THEME_GARDEN_URL
* WIDGET_GARDEN_URL

### CODE REVIEW

**Comment by thescubageek** [comment]
@mmitchellg5 check it out

**Comment by levibrown** [comment]
:shipit:

**Comment by thescubageek** [comment]
@mmitchellg5 I tried pushing this master to the master CAC but got rejected because of conflicts... are you running an alt branch on the CAC?

**Comment by thescubageek** [comment]
Nevermind previous comment

**Pull request merged**
